<?php

namespace BaseCartBundle\Entity;

/**
 * BaseProductEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProductEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
