<?php

namespace BaseCartBundle\Entity;

/**
 * BaseShoppingCartEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseShoppingCartEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
