shopping_cart_shopping_cart_homepage:
    path:     /hello/{name}
    defaults: { _controller: ShoppingCartShoppingCartBundle:Default:index }

# shopping_cart_base_cart:
# 	path: /base/cart
# 	defaults: {_controller: ShoppingCartShoppingCartBundle:ShoppingCart:createBaseCart}
